import { useWallet } from "@solana/wallet-adapter-react";
import Head from "next/head";
import Auth from "../components/Auth";
import Guess from "../components/Guess";

export default function Home() {
  const { connected } = useWallet();
  console.log(connected);
  return (
    <div className="flex flex-col text-lg justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex justify-center">
        {connected ? <Guess /> : <Auth />}
      </div>
    </div>
  );
}
